# Generated by Django 3.2.5 on 2021-08-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_mailbox', '0008_auto_20190219_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailbox',
            name='smtp_uri',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='server_smtp'),
        ),
    ]
