# Generated by Django 3.2.5 on 2021-08-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_mailbox', '0009_mailbox_smtp_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='trusted',
            field=models.BooleanField(default=False, help_text='True if the e-mail come from our trusted platform', verbose_name='Trusted'),
        ),
    ]
